# Generated by Django 3.1.3 on 2022-06-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Adopter', 'Adopter'), ('Supporter', 'Supporter')], max_length=255, verbose_name='usertype'),
        ),
    ]
