# Generated by Django 3.1.3 on 2022-07-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220705_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
