# Generated by Django 3.1.3 on 2022-06-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220605_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='img',
            field=models.CharField(default='aaa.ima¥g', max_length=1024),
            preserve_default=False,
        ),
    ]
