# Generated by Django 3.1.3 on 2022-06-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220615_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='img',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
