# Generated by Django 3.1.3 on 2022-06-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220622_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
        migrations.AddField(
            model_name='cat',
            name='age_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='age_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
