# Generated by Django 3.1.3 on 2022-06-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220627_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='location',
            field=models.CharField(max_length=128),
        ),
    ]
