# Generated by Django 3.1.3 on 2022-07-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220720_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='adopter',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='supporter',
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='api.user'),
            preserve_default=False,
        ),
    ]
