# Generated by Django 3.1.3 on 2022-07-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220721_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.AddField(
            model_name='chat',
            name='adopter',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='chat_adopter', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='supporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_supporter', to='api.user'),
            preserve_default=False,
        ),
    ]
