# Generated by Django 3.1.3 on 2022-06-29 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220628_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='adopter',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='supporter',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
