# Generated by Django 3.1.3 on 2022-06-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='user',
        ),
    ]
